# RTMX Makefile Targets
# Generated by rtmx makefile

.PHONY: rtm backlog health deps cycles verify

# Show RTM status
rtm:
	@rtmx status

# Show prioritized backlog
backlog:
	@rtmx backlog

# Run health check
health:
	@rtmx health

# Show dependency graph
deps:
	@rtmx deps

# Check for cycles
cycles:
	@rtmx cycles

# Verify test coverage
verify:
	@rtmx verify

# Verify and update status
verify-update:
	@rtmx verify --update

# Show workable requirements
workable:
	@rtmx deps --workable

# Initialize new project
init:
	@rtmx init

# Reconcile dependencies
reconcile:
	@rtmx reconcile

# Reconcile and fix
reconcile-fix:
	@rtmx reconcile --execute

# Filter backlog by phase
backlog-phase:
	@rtmx backlog --phase $(PHASE)

# Show critical path
critical:
	@rtmx backlog --view critical

# Show quick wins
quick-wins:
	@rtmx backlog --view quick-wins
