package opencode

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/rtmx-ai/aegis-cli/internal/index"
)

// RepoMapFile is the auto-generated repo-map instruction file. aegis stages it at
// interactive launch and RenderConfig injects it into the system prompt, so the
// model always has the codebase skeleton (real symbols to call) WITHOUT having to
// invoke /map (INDEX-001, context-builder mode). /map remains for an on-demand,
// task-focused refresh.
const RepoMapFile = "repo-map.md"

// StageRepoMap builds a bounded, model-free repo map of root and writes it into
// seedDir as RepoMapFile. Best-effort: returns false (and stages nothing) when
// there is no Go source to map or the write fails — the launch proceeds either way.
func StageRepoMap(seedDir, root string) bool {
	out, err := index.Build(index.Options{Root: root, TokenBudget: 6000})
	if err != nil || strings.TrimSpace(out) == "" {
		return false
	}
	body := "# Repository map (auto-generated by aegis via static analysis — no model)\n\n" +
		"A ranked skeleton of this codebase. Prefer calling these real symbols over guessing or loading whole files.\n\n" +
		out
	return os.WriteFile(filepath.Join(seedDir, RepoMapFile), []byte(body), 0o644) == nil
}

func fileExists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}
