package opencode

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"time"

	"github.com/rtmx-ai/aegis-cli/internal/config"
)

// This is the headless agent-run surface (BENCH-001): aegis drives OpenCode
// through its `serve` HTTP API (openapi.json) rather than the interactive TUI.
// The real contract, reverse-engineered against v1.17.9:
//   - routes live under /api; readiness is GET /openapi.json (200, unauthenticated)
//   - auth is HTTP Basic; the password is generated by serve into a state file
//     (Global.Path.state/password); username defaults to "opencode"
//   - flow: POST /api/session {agent,model,location} -> POST /api/session/{id}/prompt
//     -> observe via GET /api/session/{id}/message (the /wait endpoint is a stub
//     in this preview: "Session wait is not available yet")
//
// KNOWN UPSTREAM GAP (v1.17.9 OpenCode 2.0 preview): an admitted prompt is not
// actually run through the public HTTP surface — messages never populate and
// /wait is unimplemented. The client below is correct for when upstream lands the
// headless run; see docs/requirements/intent-bench.md. We drive OpenCode; we do
// not reimplement it.

// airgapEnv is the hardened launch environment shared by the TUI launch and the
// serve API: air-gap markers + the operator's model rendered inline (OC-006).
func airgapEnv(cfg config.Config) []string {
	return []string{
		"OPENCODE_AUTOUPDATE=0",
		"OPENCODE_TELEMETRY=0",
		"OPENCODE_DISABLE_SHARE=1",
		"OPENAI_BASE_URL=" + cfg.Endpoint + "/v1",
		"OPENAI_API_KEY=not-needed-loopback",
		"OPENCODE_CONFIG_CONTENT=" + RenderConfig(cfg),
	}
}

// Tokens is the per-message usage OpenCode reports (used for intent-bench).
type Tokens struct {
	Total     float64 `json:"total"`
	Input     float64 `json:"input"`
	Output    float64 `json:"output"`
	Reasoning float64 `json:"reasoning"`
}

// TranscriptMessage is one flattened message from a session (role + usage + text).
type TranscriptMessage struct {
	Role   string
	Tokens Tokens
	Cost   float64
	Finish string
	Text   string
}

// ServeClient is an HTTP client for a running `opencode serve` API.
type ServeClient struct {
	base  string
	hc    *http.Client
	auth  string // "Basic ..." header value, when the server requires it
	dir   string // working directory the session is rooted at
	agent string // OpenCode agent (e.g. "build")
}

// NewServeClient returns a client for the serve API at base (e.g.
// "http://127.0.0.1:8099"). Exported so tests can drive it against a mock.
func NewServeClient(base string) *ServeClient {
	return &ServeClient{base: base, hc: &http.Client{Timeout: 30 * time.Minute}, agent: "build"}
}

// SetAuth sets HTTP Basic credentials for the session routes.
func (c *ServeClient) SetAuth(username, password string) {
	if password == "" {
		return
	}
	c.auth = "Basic " + base64.StdEncoding.EncodeToString([]byte(username+":"+password))
}

func (c *ServeClient) do(ctx context.Context, method, path string, body, out any) error {
	var rdr io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return err
		}
		rdr = bytes.NewReader(b)
	}
	req, err := http.NewRequestWithContext(ctx, method, c.base+path, rdr)
	if err != nil {
		return err
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if c.auth != "" {
		req.Header.Set("Authorization", c.auth)
	}
	resp, err := c.hc.Do(req)
	if err != nil {
		return fmt.Errorf("opencode serve %s %s: %w", method, path, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode/100 != 2 {
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 2048))
		return fmt.Errorf("opencode serve %s %s: %s: %s", method, path, resp.Status, b)
	}
	if out != nil {
		return json.NewDecoder(resp.Body).Decode(out)
	}
	return nil
}

// Ready reports whether the serve API is up (GET /openapi.json, unauthenticated).
func (c *ServeClient) Ready(ctx context.Context) bool {
	return c.do(ctx, http.MethodGet, "/openapi.json", nil, &json.RawMessage{}) == nil
}

// CreateSession opens a session rooted at the working dir with the agent + model.
func (c *ServeClient) CreateSession(ctx context.Context, model Model) (string, error) {
	body := map[string]any{
		"agent":    c.agent,
		"model":    map[string]any{"providerID": model.ProviderID, "id": model.ModelID},
		"location": map[string]any{"directory": c.dir},
	}
	var resp struct {
		Data struct {
			ID string `json:"id"`
		} `json:"data"`
	}
	if err := c.do(ctx, http.MethodPost, "/api/session", body, &resp); err != nil {
		return "", err
	}
	if resp.Data.ID == "" {
		return "", errors.New("opencode serve: empty session id")
	}
	return resp.Data.ID, nil
}

// Model identifies the provider+model for a prompt.
type Model struct {
	ProviderID string
	ModelID    string
}

// Prompt admits a text prompt to the session (one autonomous agent turn).
func (c *ServeClient) Prompt(ctx context.Context, sessionID, text string) error {
	body := map[string]any{"prompt": map[string]any{"text": text}}
	return c.do(ctx, http.MethodPost, "/api/session/"+sessionID+"/prompt", body, nil)
}

// Messages returns the session transcript, flattened to role + usage + text.
func (c *ServeClient) Messages(ctx context.Context, sessionID string) ([]TranscriptMessage, error) {
	var resp struct {
		Data []struct {
			Info struct {
				Role   string  `json:"role"`
				Tokens Tokens  `json:"tokens"`
				Cost   float64 `json:"cost"`
				Finish string  `json:"finish"`
			} `json:"info"`
			Parts []struct {
				Type string `json:"type"`
				Text string `json:"text"`
			} `json:"parts"`
		} `json:"data"`
	}
	if err := c.do(ctx, http.MethodGet, "/api/session/"+sessionID+"/message", nil, &resp); err != nil {
		return nil, err
	}
	out := make([]TranscriptMessage, 0, len(resp.Data))
	for _, m := range resp.Data {
		tm := TranscriptMessage{Role: m.Info.Role, Tokens: m.Info.Tokens, Cost: m.Info.Cost, Finish: m.Info.Finish}
		for _, p := range m.Parts {
			if p.Type == "text" {
				tm.Text += p.Text
			}
		}
		out = append(out, tm)
	}
	return out, nil
}

// statePassword reads the serve password OpenCode generated into its state dir.
func statePassword() string {
	dir := os.Getenv("XDG_STATE_HOME")
	if dir == "" {
		if home, err := os.UserHomeDir(); err == nil {
			dir = filepath.Join(home, ".local", "state")
		}
	}
	b, err := os.ReadFile(filepath.Join(dir, "opencode", "password"))
	if err != nil {
		return ""
	}
	return string(bytes.TrimSpace(b))
}

// StartServe launches `opencode serve` rooted at workdir under the hardened,
// operator-rendered config, waits for readiness, and authenticates with the
// generated state password. The returned stop function terminates the server.
func StartServe(ctx context.Context, bin string, cfg config.Config, workdir string, port int) (*ServeClient, func(), error) {
	cmd := exec.CommandContext(ctx, bin, "serve", "--hostname", "127.0.0.1", "--port", strconv.Itoa(port))
	cmd.Dir = workdir
	cmd.Env = append(os.Environ(), airgapEnv(cfg)...)
	cmd.Stdout, cmd.Stderr = os.Stderr, os.Stderr
	if err := cmd.Start(); err != nil {
		return nil, nil, fmt.Errorf("opencode serve: start: %w", err)
	}
	stop := func() {
		_ = cmd.Process.Kill()
		_, _ = cmd.Process.Wait()
	}
	c := NewServeClient(fmt.Sprintf("http://127.0.0.1:%d", port))
	c.dir = workdir
	deadline := time.Now().Add(30 * time.Second)
	for time.Now().Before(deadline) {
		if c.Ready(ctx) {
			c.SetAuth("opencode", statePassword())
			return c, stop, nil
		}
		time.Sleep(200 * time.Millisecond)
	}
	stop()
	return nil, nil, errors.New("opencode serve: API did not become ready within 30s")
}
